### ISSUE TITLE
support for dash in endpoint

### ISSUE THREAD

**Issue by dginhoux** [enix/routeros-rest-exporter#1]
Hi, 

Thank you for your work. I use your work for monitor few devices, routers, accesspoints and switches.
I get an error for endpoint with dash like : `interface/wifi/registration-table` ; error is `ValueError: Invalid metric name: routeros_interface_wifi_registration-table_rx_rate`.

**And yes, openmetrics don't use dash, only underscore.**

So i made the following modifications : 
In yml endpoints file, i add an url attributes (needed everywhere) : 

```yaml
  interface/wifi/registration_table:
    url: interface/wifi/registration-table
    metrics:
      - name: rx-rate
  system/resource/cpu:
    url: ""
    metrics:
      - name: load
```

In python script near line 200, to override path by the attribute url if set : 
```python
                url = f"https://{target['hostname']}:{target['port']}/rest/{path}"
                if endpoint["url"]:
                    url = f"https://{target['hostname']}:{target['port']}/rest/{endpoint['url']}"
```

Maybe it can be better... but its easier for me.

Have a good day.
